[dotfiles] # dotfiles to add when `dotfiles update`


[dotfiles.submodules] # move the submodules to their proper place
awesome-dotfiles

[commands] # run '''as is'''
curl -sS https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg | gpg --import -

[sys.environment]
LV_BRANCH="release-1.3/neovim-0.9"
XDG_DOWNLOAD_DIR="${HOME}/Downloads"
ZSH="~/.bin/.oh-my-zsh"
ZSH_CUSTOM="~/.bin/.oh-my-zsh/custom"
ZDOTDIR="$HOME/.config"

[sys.dir] # mkdir -p ~/{LINE}
Documents
Downloads
Pictures
Trash

[sys.fonts] # placed in ~/.local/share/fonts/
https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf MesloLGS
https://github.com/stwgabriel/SF-fonts/blob/master/SFPro/TrueType/SFProDisplay-Regular.ttf SFPro

[sys.packages] # install things with aura -S
acpi
alsa-utils				# sound utils
awesome					# wm
bc						# calculator

alacritty				# terminal

keepassxc				# password manager

firefox					# default browser

bluez					# bluetooth manager
bluez-utils				# bluetooth manager
blueman					# graphical bluetooth control

cargo					# dev
cmatrix					# ascii art
dex						# awesome autostart
discord					# optional
feh

gcc						# dev
gdb						# dev
lazygit					# dev
npm						# dev
python					# dev

man-db					# docs
man-pages				# docs
texinfo 				# docs

i3lock
imagemagick
luakit
nautilus
neofetch
neovim					# editor
nm-connection-editor
openssh					# ssh
picom					# pretty windows
redshift				# tint screen depending on time of day
rofi					# menu
scrot
unclutter				# hide the mouse when not in use
xorg-xbacklight
xdg-utils

zsh

mesa					# nvidia specific driver
xf86-video-nouveau		# nvidia specific driver

xfce4-power-manager

xorg-xinit				# wm autostart
xorg-xrdb				# awesome autostart
xorg-server				# wm
xorg-xrandr				# multimonitor support


[sys.aur] # install things with aura -A
spotify					# optional
thorium-browser-bin
vscodium

[git] # git clone https://github.com/{LINE}
zsh-users/zsh-autosuggestions ~/.bin/.oh-my-zsh/custom/plugins/zsh-autosuggestions
zsh-users/zsh-syntax-highlighting ~/.bin/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

[scripts] # {sh|bash} -c "$(curl -fsSL https://raw.github.com/{url})
sh ohmyzsh/ohmyzsh/master/tools/install.sh
sh spicetify/spicetify-cli/master/install.sh
bash LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh

[commands] # run  '''as is'''
# install spicitify
sudo chown $USER -R /opt/spotify
spicetify
spicetify backup apply enable-devtool
spicetify update restart
# update some defaults
xdg-settings set default-web-browser thorium-browser.desktop
xdg-mime default thorium-browser.desktop x-scheme-handler/http
xdg-mime default thorium-browser.desktop x-scheme-handler/https
# install powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k
